MODEL:
  TYPE: adapter_swin_diffusion_finetune
  NAME: adapter_swin_diffusion_finetune_base_patch4_window7_224_22kto1k_dt2
  DROP_PATH_RATE: 0.2
  VCNU_SWIN:
    PRETRAIN_IMAGE_SIZE: 224
    MODEL_STYLE: trans
    TRAINING_MODE: tfs

    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
  EFFICIENT_FINETUNE: True
  FINETUNE_MODE: dt2
SAVE_FREQ: 15